import { useState } from "react";
import PageHeader from "../components/common/PageHeader";
import { ArrowRight, CheckCircle2, Cpu, Eye, Filter, Grid, Layers, Sparkles } from "lucide-react";

export default function HowItWorksPage() {
  const [selectedStepIndex, setSelectedStepIndex] = useState(0);

  const steps = [
    {
      num: "01",
      title: "Input image",
      purpose: "Acquires user-submitted specimen in JPEG or PNG format.",
      input: "Raw image bytes (>= 512×512 px, sRGB color).",
      output: "Uncompressed RGB tensor.",
      trainable: "No (Preprocessing)",
      explanation:
        "The uploaded image is verified for supported MIME types and minimal dimensions. EXIF orientation metadata is parsed and normalized to guarantee deterministic orientation prior to downstream spatial operations.",
    },
    {
      num: "02",
      title: "512×512 center crop",
      purpose: "Extracts an un-interpolated spatial window to avoid resampling distortions.",
      input: "Full-resolution RGB tensor [3, H, W].",
      output: "Standardized spatial crop [3, 512, 512].",
      trainable: "No (Deterministic Crop)",
      explanation:
        "Resizing introduces artificial interpolation kernels (such as bilinear or bicubic sinc ringing) that pollute high-frequency spectra. MaskSim strictly extracts a 512×512 center crop, ensuring zero scale distortion on the underlying sensor noise.",
    },
    {
      num: "03",
      title: "RGB → YCbCr conversion",
      purpose: "Separates luminance from chrominance frequency components.",
      input: "RGB tensor in range [0, 1].",
      output: "YCbCr tensor: Y (luma), Cb (chroma blue), Cr (chroma red).",
      trainable: "No (Color Matrix)",
      explanation:
        "Generative autoencoders frequently display channel-correlated artifacts. Converting to ITU-R BT.601 YCbCr decorrelates visual image structure, enabling independent analysis of high-frequency chromatic variations.",
    },
    {
      num: "04",
      title: "DnCNN residual extraction",
      purpose: "Suppresses semantic scene content to expose noise residual structure.",
      input: "Standardized 512×512 YCbCr tensor.",
      output: "Noise residual R = X - DnCNN(X) [3, 512, 512].",
      trainable: "Frozen Pretrained Weights (20 layers, 668,227 parameters)",
      explanation:
        "DnCNN acts as a high-pass residual operator. By subtracting the denoised estimate from the input patch, low-frequency scene semantics (faces, objects, backgrounds) are suppressed, isolating subtle sensor and generative artifacts.",
    },
    {
      num: "05",
      title: "2D Fast Fourier Transform (FFT)",
      purpose: "Transforms spatial noise residual into the 2D frequency domain.",
      input: "Spatial residual tensor [3, 512, 512].",
      output: "Complex 2D frequency spectrum F(u, v) [3, 512, 512].",
      trainable: "No (Orthogonal 2D-FFT)",
      explanation:
        "Evaluates 2D discrete Fourier transforms independently for each color channel using orthonormal normalization (norm='ortho'). Periodic grid patterns generated by latent upsampling appear as localized spatial frequencies.",
    },
    {
      num: "06",
      title: "FFT centered shift (fftshift)",
      purpose: "Reorganizes quadrant zero-frequencies to the visual center of the spectrum.",
      input: "Unshifted frequency spectrum F(u, v).",
      output: "Zero-frequency centered spectrum with DC at (0, 0).",
      trainable: "No (Quadrantal Shift)",
      explanation:
        "Executes a standard quadrant swap (fftshift) exactly once so that zero frequency (DC) sits at coordinate (0, 0), with spatial frequencies increasing symmetrically outward to the Nyquist limits (±256).",
    },
    {
      num: "07",
      title: "Log-magnitude representation",
      purpose: "Compresses high-dynamic-range spectral power for linear network analysis.",
      input: "Centered complex spectrum F(u, v).",
      output: "Log magnitude: S(u, v) = log(1 + |F(u, v)|).",
      trainable: "No (Nonlinear Mapping)",
      explanation:
        "Fourier magnitudes span multiple orders of magnitude. The log(1 + |F(u, v)|) formulation compresses dynamic range with numerical stability, preventing central low-frequency components from dominating the learned detector layers.",
    },
    {
      num: "08",
      title: "Learned frequency mask",
      purpose: "Applies channel-specific learned spatial attention to diagnostic frequency bins.",
      input: "Log-magnitude spectral tensor [3, 512, 512].",
      output: "Masked spectral tensor M ⊙ S [3, 512, 512].",
      trainable: "Yes (1×1 Conv + BatchNorm + Sigmoid, 1,572,884 parameters)",
      explanation:
        "A learned 2D attention mask emphasizes frequency coordinates where Stable Diffusion 1.4 autoencoders exhibit systematic lattice harmonics (such as the 8×8 decimation grid peaks) while dampening irrelevant camera frequencies.",
    },
    {
      num: "09",
      title: "Learned reference spectrum",
      purpose: "Provides a learned canonical synthetic archetype vector.",
      input: "Learned reference parameter vector.",
      output: "Canonical synthetic fingerprint prototype R_synth.",
      trainable: "Yes (Optimized Reference Vector)",
      explanation:
        "Rather than relying on uninterpretable deep feature embeddings, MaskSim learns an archetype spectrum representing the prototypical Stable Diffusion 1.4 synthetic fingerprint across thousands of training samples.",
    },
    {
      num: "10",
      title: "Cosine similarity projection",
      purpose: "Measures directional alignment between masked spectrum and canonical reference.",
      input: "Masked spectrum vector and learned reference vector.",
      output: "Scalar cosine similarity s = cos(θ) ∈ [-1, 1].",
      trainable: "No (Vector Dot Product)",
      explanation:
        "Computes the normalized dot product s = (v_spec · v_ref) / (||v_spec|| ||v_ref||). This measures geometric alignment invariant to overall image brightness or residual amplitude variations.",
    },
    {
      num: "11",
      title: "Detector score & classification",
      purpose: "Maps similarity score through logistic scaling to produce final detector score.",
      input: "Cosine similarity s.",
      output: "Final detector score ∈ [0, 1] and prediction (AI_GENERATED vs REAL).",
      trainable: "Calibrated Decision Boundary (Threshold = 0.5000)",
      explanation:
        "The similarity metric is transformed into the final detector score. Scores at or above 0.5000 indicate synthetic fingerprint match. The score reflects evidence alignment specifically calibrated for Stable Diffusion 1.4.",
    },
  ];

  const currentStep = steps[selectedStepIndex];

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "36px" }}>
      <PageHeader
        eyebrow="Pipeline Methodology"
        title="How MaskSim Works"
        description="A deterministic 11-step forensic pipeline combining spatial residual filtering, 2D Fourier transforms, and learned frequency attention."
      />

      {/* Main Educational Stepper Interface */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
          gap: "28px",
          alignItems: "start",
        }}
      >
        {/* Left Column: Interactive Step Selector */}
        <div className="card" style={{ padding: "16px" }}>
          <div style={{ fontSize: "12px", fontWeight: 600, color: "var(--text-secondary)", textTransform: "uppercase", letterSpacing: "0.04em", padding: "8px 12px", marginBottom: "8px" }}>
            Pipeline Steps
          </div>

          <div style={{ display: "flex", flexDirection: "column", gap: "4px" }}>
            {steps.map((step, idx) => {
              const isSelected = selectedStepIndex === idx;
              return (
                <button
                  key={step.num}
                  type="button"
                  onClick={() => setSelectedStepIndex(idx)}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: "12px",
                    padding: "10px 14px",
                    borderRadius: "var(--radius-md)",
                    background: isSelected ? "var(--bg-subtle)" : "transparent",
                    border: isSelected ? "1px solid var(--accent-border)" : "1px solid transparent",
                    textAlign: "left",
                    transition: "all 0.15s ease",
                  }}
                >
                  <span
                    className="mono"
                    style={{
                      fontSize: "12px",
                      fontWeight: 700,
                      color: isSelected ? "var(--accent-blue)" : "var(--text-muted)",
                      width: "22px",
                    }}
                  >
                    {step.num}
                  </span>
                  <span
                    style={{
                      fontSize: "13.5px",
                      fontWeight: isSelected ? 650 : 500,
                      color: isSelected ? "var(--accent-blue)" : "var(--text-primary)",
                      flex: 1,
                    }}
                  >
                    {step.title}
                  </span>
                </button>
              );
            })}
          </div>
        </div>

        {/* Right Column: Detailed Step Inspector */}
        <div className="card" style={{ display: "flex", flexDirection: "column", gap: "20px" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
            <div>
              <div className="mono" style={{ fontSize: "12px", fontWeight: 700, color: "var(--accent-blue)" }}>
                STEP {currentStep.num} OF 11
              </div>
              <h2 style={{ fontSize: "22px", fontWeight: 750, color: "var(--text-primary)", marginTop: "4px" }}>
                {currentStep.title}
              </h2>
            </div>
            <span
              className="navbar-badge"
              style={{
                color: currentStep.trainable.startsWith("Yes") ? "var(--accent-blue)" : "var(--text-muted)",
              }}
            >
              {currentStep.trainable.split(" ")[0]}
            </span>
          </div>

          <div className="card-subtle" style={{ fontSize: "14px", lineHeight: 1.6, color: "var(--text-primary)" }}>
            {currentStep.explanation}
          </div>

          <div
            style={{
              display: "flex",
              flexDirection: "column",
              gap: "12px",
              padding: "16px",
              background: "var(--bg-subtle)",
              borderRadius: "var(--radius-md)",
              border: "1px solid var(--border-subtle)",
              fontSize: "13px",
            }}
          >
            <div>
              <div style={{ fontSize: "11px", fontWeight: 600, color: "var(--text-secondary)", textTransform: "uppercase" }}>
                Purpose
              </div>
              <div style={{ color: "var(--text-primary)", marginTop: "2px", fontWeight: 500 }}>
                {currentStep.purpose}
              </div>
            </div>

            <div style={{ borderTop: "1px solid var(--border-subtle)", paddingTop: "10px" }}>
              <div style={{ fontSize: "11px", fontWeight: 600, color: "var(--text-secondary)", textTransform: "uppercase" }}>
                Input Specification
              </div>
              <div className="mono" style={{ color: "var(--text-primary)", marginTop: "2px" }}>
                {currentStep.input}
              </div>
            </div>

            <div style={{ borderTop: "1px solid var(--border-subtle)", paddingTop: "10px" }}>
              <div style={{ fontSize: "11px", fontWeight: 600, color: "var(--text-secondary)", textTransform: "uppercase" }}>
                Output Specification
              </div>
              <div className="mono" style={{ color: "var(--text-primary)", marginTop: "2px" }}>
                {currentStep.output}
              </div>
            </div>

            <div style={{ borderTop: "1px solid var(--border-subtle)", paddingTop: "10px" }}>
              <div style={{ fontSize: "11px", fontWeight: 600, color: "var(--text-secondary)", textTransform: "uppercase" }}>
                Parameter Optimization Status
              </div>
              <div style={{ color: "var(--text-primary)", marginTop: "2px" }}>
                {currentStep.trainable}
              </div>
            </div>
          </div>

          <div style={{ display: "flex", justifyContent: "space-between", marginTop: "8px" }}>
            <button
              type="button"
              className="btn-secondary"
              disabled={selectedStepIndex === 0}
              onClick={() => setSelectedStepIndex((prev) => Math.max(0, prev - 1))}
            >
              Previous Step
            </button>

            <button
              type="button"
              className="btn-primary"
              disabled={selectedStepIndex === steps.length - 1}
              onClick={() => setSelectedStepIndex((prev) => Math.min(steps.length - 1, prev + 1))}
            >
              <span>Next Step</span>
              <ArrowRight size={14} />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
